### ISSUE TITLE
not working on Win11 23H2 + UI light mode issue

### ISSUE THREAD

**Issue by bel57** [SamsidParty/TopNotify#1]
Hello,
I've noticed your post on reddit so decided to test your app.
For some reason your screenshot is different than how the app behaves on my PC, first the text is black instead of white in light mode. I'm using Auto Dark mode to switch to dark mode when it's the night.
And when I click to spawn a test notification nothing shows up. Restarting the app and spamming test spawn, I've had a notification from TopNotify pop up only once and in the wrong corner (still bottom right).
I don't have DND/focus mode enabled. On the other hand, notifications keep spawning with the normal Windows UI in the bottom right corner.

I'd like to provide logs but I don't see anything in C:\Users\Bel\AppData\Local\SamsidParty\TopNotify\Log.txt it's just lines of "working directory" / "Base directory" / "Exe located"

TopNotify v2.1.1
Win11 23H2

Here's the difference with yours on left and mine on right:
![image](https://github.com/SamsidParty/TopNotify/assets/10614811/b258cb5a-959a-46bf-b9c4-e129e5e23024)

Thanks!

**Comment by SamarthMP** [comment]
By any chance, do you have your system language set to anything other than english?

As for the UI, I was able to reproduce the issue, the reason it's like this is because the ShouldSystemUseDarkMode returns a different value than the WebView2 css value. I will try and fix it in IgniteView.

**Comment by SamarthMP** [comment]
The UI issue has been fixed, turns out ShouldAppsUseDarkMode returns a bogus value, and ShouldSystemUseDarkMode returns the system value. I still need more info to diagnose why the notifications aren't working.

**Comment by bel57** [comment]
Thanks for the quick fix. Text is now visible.
However notifications from TopNotify are still not displayed, clicking spawn test does nothing :(
Yes system language is FR-FR

**Comment by SamarthMP** [comment]
Ah, I see, I believe this is because the notification window has a different title in different languages.
Would you be willing to temporarily change to en_us or en_gb to test if it works? Then I can work on a patch.

**Comment by bel57** [comment]
I see. Knowing Windows, switching system with another language will mess things up so I'm not keen to do that.

**Comment by SamarthMP** [comment]
Alright, do you have visual studio installed by any chance?
If not, I can spin up a quick french virtual machine and go from there.

**Comment by bel57** [comment]
I do not, sorry :/ I've tried the app in Windows sandbox but it crashes when launched from systray.
Looks like some components are missing in the virtual environment.

**Comment by SamarthMP** [comment]
Alright, well I'm creating a virtual machine right now, I'll get back to you when I test it.

**Comment by SamarthMP** [comment]
Ok, I can reproduce this issue in a virtual machine with the language set to French.
I am currently working on a fix, hopefully it will be out today if all goes well.

**Comment by bel57** [comment]
Much appreciated! There's very little text to translate but let me know if you have a strings file or something for the options.

**Comment by SamarthMP** [comment]
I have released version 2.1.3, which adds support for French notifications in the interceptor.
I will be working to add more languages and better support in future versions.
Please check if it works, and report any other issues to me.

**Comment by bel57** [comment]
Thanks, it's working now. Spawn test notification still broken, though.
I've send a message to myself over discord with an alt, could you fix the position for users who have the taskbar on top position instead of bottom of the screen? TopNotify notification is overlapping 10px over the taskbar.
If you could respect Win11 UI and put a padding of 15px so there's a slight gap between both, that would be great.
![image](https://github.com/SamsidParty/TopNotify/assets/10614811/936d964e-05d8-444c-a329-80dcb5e95340)

**Comment by SamarthMP** [comment]
Great! For the sake of organization, please file new issues for the "Send Test Notification" bug and the "Custom Notification Position" feature request. I will close this issue now.
